@extends('layout')
@section('content')
<style type="text/css">
	th,td {
		text-align: center;
	}
	.thu {
		width: 50px;
		height: 30px;
	}
</style>
<div>
	<!-- <form>
		<table border="1" width="100%" >
		    <tr>
		        <th rowspan="2">Thứ</th>
		        <th colspan="4">Tiết 1-2/3</th>
		        <th colspan="4">Tiết 3-4</th>
		        <th colspan="4">Tiết 5-6</th>
		        <th colspan="4">Tiết 7-8/9</th>
		        <th colspan="4">Tiết 9-10-11</th>
		        <th colspan="4">Tiết 11-12</th>
		    </tr>
		    <tr>
		        <td>GV</td>
		        <td>Môn</td>
		        <td>PMT</td>
		        <td>SL</td>
		        <td>GV</td>
		        <td>Môn</td>
		        <td>PMT</td>
		        <td>SL</td>
		        <td>GV</td>
		        <td>Môn</td>
		        <td>PMT</td>
		        <td>SL</td>
		        <td>GV</td>
		        <td>Môn</td>
		        <td>PMT</td>
		        <td>SL</td>
		        <td>GV</td>
		        <td>Môn</td>
		        <td>PMT</td>
		        <td>SL</td>
		        <td>GV</td>
		        <td>Môn</td>
		        <td>PMT</td>
		        <td>SL</td>
		    </tr>
		    <tr>
			    <th class="thu" rowspan="4">Thứ 2</th>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <th rowspan="4">Thứ 3</th>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <th rowspan="4">Thứ 4</th>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <th rowspan="4">Thứ 5</th>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <th rowspan="4">Thứ 6</th>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <th rowspan="4">Thứ 7</th>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		    <tr>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>user</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		        <td>C1</td>
		        <td>C2</td>
		        <td>C3</td>
		    </tr>
		</table>
	</form> -->
	<form method="get" class="searchform" action="{{ route('search')}}" role="search"> 
	    <input type="search" name="search" class="form-control" placeholder="Tìm Kiếm ..." style="float: left;" />
	    <button type="submit" name="" class="btn btn-info" style="height: 38px;">
	    	<i class="fa fa-search"></i>
	    </button>
	</form>
	<div class="table-agile-info">
	  <div class="panel panel-default">
	    <div class="panel-heading text-center">
	      <h4>Thời Khóa Biểu </h4>
	    </div>
	    <div class="table-responsive">
	      <table class="table table-striped b-t b-light">
	        <thead>
	          <tr>
	            <th>Môn Học</th>
	            <th>Tên GV</th>
	            <th>Thứ</th>
	            <th>Từ Tiết</th>
	            <th>Đến Tiết</th>
	            <th>SL</th> 
	            <th>Mã PMT</th>
	          </tr>
	        </thead>
	        <tbody>
	          @foreach($search_tkb as $key => $cate)
	          <tr>
	            <td>{{ $cate->MaMH }}</td>
	            <td>{{ $cate->TenGV }}</td>
	            <td>{{ $cate->Thu }}</td>
	            <td>{{ $cate->TuTiet }}</td>
	            <td>{{ $cate->DenTiet }}</td>
	            <td>{{ $cate->SoLuongSV }}</td>
	            <td>{{ $cate->MaPMT }}</td>
	          </tr>
	          @endforeach
	        </tbody>
	      </table>
	    </div>
	  </div>
	</div>
</div>
@endsection